import alfaRomeoSprint from '../assets/images/alfa-romeo-sprint.jpg';
import astonMartinDB from '../assets/images/aston-martin-DB.jpg';
import austinHealey3000MkII from '../assets/images/austin-healey-3000MkII.jpg';
import austinHealey from '../assets/images/austin-healey.jpg';
import bmw1600 from '../assets/images/bmw-1600.jpg';
import cadilacSixty from '../assets/images/cadilac-sixty.jpg';
import chevroletCamaro from '../assets/images/chevrolet-camaro.jpg';
import ferrari365 from '../assets/images/ferrari-365.jpg';
import ferrari512BB from '../assets/images/ferrari-512BB.jpg';
import topolino from '../assets/images/FIAT-500topolino.jpg';
import fordShelbyGT500 from '../assets/images/ford-shelby-GT-500.jpg';
import jaguarXK150 from '../assets/images/jaguar-XK150.jpg';
import lamborghiniEspada from '../assets/images/lamborghini-espada.jpg';
import mercedesBenz180 from '../assets/images/mercedes-benz-180.jpg';
import mercedesBenz300SLRoadster from '../assets/images/mercedes-benz-300-SL-roadster.jpg';
import pontiacGTO from '../assets/images/pontiac-GTO.jpg';
import porsche356A from '../assets/images/porsche-356A.jpg';
import porsche911 from '../assets/images/porsche-911.jpg';
import porsheSpeedster from '../assets/images/porshe-speedster.jpg';
import silverCloud from '../assets/images/silver-cloud.jpg';
import triumphTr3a from '../assets/images/triumph-tr3a.jpg';
import volkswagenBeetle from '../assets/images/volkswagen-beetle.jpg';

export const cardDB = [
  {
    id: 'car01',
    image: topolino,
    brand: 'FIAT',
    model: 'Topolino 500 A',
    year: '1940',
    color: 'Серый',
    colorID: 'grey',
    favorite: false,
    doors: '2',
    volume: '13',
    owners: '4',
    inBasket: false,
  },
  {
    id: 'car02',
    image: austinHealey,
    brand: 'Austin-Healey',
    model: '100 /4',
    year: '1954',
    color: 'Зеленый',
    colorID: 'green',
    favorite: true,
    doors: '2',
    volume: '102',
    owners: '4',
    inBasket: false,
  },
  {
    id: 'car03',
    image: silverCloud,
    brand: 'Rolls-Royce',
    model: 'Silver Cloud',
    year: '1960',
    color: 'Черный',
    colorID: 'black',
    favorite: true,
    doors: '2',
    volume: '92',
    owners: '1',
    inBasket: false,
  },
  {
    id: 'car04',
    image: triumphTr3a,
    brand: 'Triumph',
    model: 'TR3A',
    year: '1958',
    color: 'Красный',
    colorID: 'red',
    favorite: true,
    doors: '2',
    volume: '100',
    owners: '2',
    inBasket: false,
  },
  {
    id: 'car05',
    image: porsche911,
    brand: 'Porsche',
    model: '911',
    year: '1973',
    color: 'Черный',
    colorID: 'black',
    favorite: true,
    doors: '2',
    volume: '249',
    owners: '3',
    inBasket: false,
  },
  {
    id: 'car06',
    image: cadilacSixty,
    brand: 'CADILLAC',
    model: 'SIXTY SPECIAL',
    year: '1960',
    color: 'Красный',
    colorID: 'red',
    favorite: false,
    doors: '4',
    volume: '330',
    owners: '3',
    inBasket: false,
  },
  {
    id: 'car07',
    image: chevroletCamaro,
    brand: 'Chevrolet',
    model: 'Camaro Z28',
    year: '1979',
    color: 'Черный',
    colorID: 'black',
    favorite: true,
    doors: '2',
    volume: '360',
    owners: '1',
    inBasket: false,
  },
  {
    id: 'car08',
    image: porsheSpeedster,
    brand: 'Porsche',
    model: '356 1500 Speedster',
    year: '1955',
    color: 'Белый',
    colorID: 'white',
    favorite: false,
    doors: '2',
    volume: '55',
    owners: '2',
    inBasket: false,
  },
  {
    id: 'car09',
    image: jaguarXK150,
    brand: 'Jaguar',
    model: 'XK 150',
    year: '1960',
    color: 'Черный',
    colorID: 'black',
    favorite: true,
    doors: '2',
    volume: '223',
    owners: '5',
    inBasket: false,
  },
  {
    id: 'car10',
    image: mercedesBenz300SLRoadster,
    brand: 'Mercedes-Benz',
    model: '300 SL Roadster',
    year: '1963',
    color: 'Серый',
    colorID: 'grey',
    favorite: true,
    doors: '2',
    volume: '215',
    owners: '1',
    inBasket: false,
  },
  {
    id: 'car11',
    image: bmw1600,
    brand: 'BMW',
    model: '1600 GT Coupe',
    year: '1968',
    color: 'Красный',
    colorID: 'red',
    favorite: true,
    doors: '2',
    volume: '105',
    owners: '2',
    inBasket: false,
  },
  {
    id: 'car12',
    image: alfaRomeoSprint,
    brand: 'Alfa Romeo',
    model: 'Sprint',
    year: '1964',
    color: 'Серый',
    colorID: 'grey',
    favorite: false,
    doors: '2',
    volume: '145',
    owners: '4',
    inBasket: false,
  },
  {
    id: 'car13',
    image: pontiacGTO,
    brand: 'Pontiac',
    model: 'GTO',
    year: '1967',
    color: 'Черный',
    colorID: 'black',
    favorite: true,
    doors: '2',
    volume: '360',
    owners: '2',
    inBasket: false,
  },
  {
    id: 'car14',
    image: ferrari365,
    brand: 'Ferrari',
    model: '365 GT 2+2',
    year: '1969',
    color: 'Красный',
    colorID: 'red',
    favorite: false,
    doors: '2',
    volume: '320',
    owners: '1',
    inBasket: false,
  },
  {
    id: 'car15',
    image: mercedesBenz180,
    brand: 'Mercedes-Benz',
    model: '180 D',
    year: '1955',
    color: 'Красный',
    colorID: 'red',
    favorite: true,
    doors: '4',
    volume: '40',
    owners: '3',
    inBasket: false,
  },
  {
    id: 'car16',
    image: volkswagenBeetle,
    brand: 'Volkswagen',
    model: 'Beetle',
    year: '1955',
    color: 'Серый',
    colorID: 'grey',
    favorite: true,
    doors: '2',
    volume: '30',
    owners: '4',
    inBasket: false,
  },
  {
    id: 'car17',
    image: astonMartinDB,
    brand: 'Aston Martin',
    model: 'DB 2/4 Mk I',
    year: '1955',
    color: 'Зеленый',
    colorID: 'green',
    favorite: false,
    doors: '2',
    volume: '140',
    owners: '1',
    inBasket: false,
  },
  {
    id: 'car18',
    image: porsche356A,
    brand: 'Porsche',
    model: '356 Coupé GT',
    year: '1956',
    color: 'Серый',
    colorID: 'grey',
    favorite: true,
    doors: '2',
    volume: '60',
    owners: '1',
    inBasket: false,
  },
  {
    id: 'car19',
    image: fordShelbyGT500,
    brand: 'Ford Shelby',
    model: 'GT 500',
    year: '1968',
    color: 'Серый',
    colorID: 'grey',
    favorite: true,
    doors: '2',
    volume: '335',
    owners: '2',
    inBasket: false,
  },
  {
    id: 'car20',
    image: ferrari512BB,
    brand: 'Ferrari',
    model: '512 BB',
    year: '1979',
    color: 'Синий',
    colorID: 'blue',
    favorite: false,
    doors: '2',
    volume: '360',
    owners: '1',
    inBasket: false,
  },
  {
    id: 'car21',
    image: austinHealey3000MkII,
    brand: 'Austin-Healey',
    model: '3000 Mk II',
    year: '1963',
    color: 'Красный',
    colorID: 'red',
    favorite: true,
    doors: '2',
    volume: '131',
    owners: '3',
    inBasket: false,
  },
  {
    id: 'car22',
    image: lamborghiniEspada,
    brand: 'Lamborghini',
    model: 'Espada Series III',
    year: '1974',
    color: 'Красный',
    colorID: 'red',
    favorite: true,
    doors: '2',
    volume: '350',
    owners: '1',
    inBasket: false,
  },
];
